apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: terraform-provider-rhcs-igyt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: terraform-provider-rhcs-igyt
    app.kubernetes.io/part-of: appstudio
  name: terraform-provider-rhcs-igyt
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: terraform-provider-rhcs-igyt
status:
  loadBalancer: {}
